name: Flutter Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: package.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Dockerfile to prior building
        run: cp ./cicd/Dockerfile ./dist/
      - name: Copy nodemodules to the new generated lib
        run: cp -r node_modules ./dist/
      - name: LS
        run: echo "abcd" > ${{ steps.package-version.outputs.current-version}}
      - name: LS
        run: ls ./dist

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push
        uses: docker/build-push-action@v4
        with:
          context: "./dist"
          push: true
          tags: ifloor/elastic-notifier:${{ steps.package-version.outputs.current-version}}